### ISSUE TITLE
[GUI] Popup window always in same position

### ISSUE THREAD

**Issue by ReneJurack** [HaythamB/TAMV#22]
The popup windows (e.g. controls for setting the CP) always open up in the same position, even if dragged to the side before.

**Comment by HaythamB** [comment]
It should always open in the middle of the window, and this is mainly to aid for when you're using a small touchscreen to run TAMV.

**Comment by well-engineered** [comment]
Could do a pre-check if it is going to be visually, then?!

**Comment by HaythamB** [comment]
So you mean if you've got enough display resolution, make sure it reopens in the same space? If yes, then I could look into it, I'm sure its something that can be supported.

**Comment by HaythamB** [comment]
OK finally tracked down the root cause: the dialog windows are being created outside of the main init() function for the application, and that is causing their position to become lost.

I will modify the code to fix this, but its going to take a couple of days, since a lot of logic is built into the init() classes of each dialog box, and that has to be pulled out and refreshed.

Removing the wontfix label!
